"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-09-01
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.quiz_leaderboard import QuizLeaderboard
    from openapi_client.model.quiz_questions import QuizQuestions
    globals()['QuizLeaderboard'] = QuizLeaderboard
    globals()['QuizQuestions'] = QuizQuestions


class Quiz(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('difficulty',): {
            'inclusive_maximum': 10,
            'inclusive_minimum': 1,
        },
        ('time_limit',): {
            'inclusive_maximum': 300,
            'inclusive_minimum': 3,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'name': (str, none_type,),  # noqa: E501
            'play_url': (str,),  # noqa: E501
            'pin': (str,),  # noqa: E501
            'topic': (str,),  # noqa: E501
            'author': (str,),  # noqa: E501
            'num_questions': (str,),  # noqa: E501
            'questions': ([QuizQuestions],),  # noqa: E501
            'difficulty': (float,),  # noqa: E501
            'time_limit': (float,),  # noqa: E501
            'leaderboard': (QuizLeaderboard,),  # noqa: E501
            'sync': (bool,),  # noqa: E501
            'active': (bool,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'image_url': (str,),  # noqa: E501
            'time_created': (datetime,),  # noqa: E501
            'updated': (datetime,),  # noqa: E501
            'self_link': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'name': 'name',  # noqa: E501
        'play_url': 'playUrl',  # noqa: E501
        'pin': 'pin',  # noqa: E501
        'topic': 'topic',  # noqa: E501
        'author': 'author',  # noqa: E501
        'num_questions': 'numQuestions',  # noqa: E501
        'questions': 'questions',  # noqa: E501
        'difficulty': 'difficulty',  # noqa: E501
        'time_limit': 'timeLimit',  # noqa: E501
        'leaderboard': 'leaderboard',  # noqa: E501
        'sync': 'sync',  # noqa: E501
        'active': 'active',  # noqa: E501
        'id': 'id',  # noqa: E501
        'image_url': 'imageUrl',  # noqa: E501
        'time_created': 'timeCreated',  # noqa: E501
        'updated': 'updated',  # noqa: E501
        'self_link': 'selfLink',  # noqa: E501
    }

    read_only_vars = {
        'id',  # noqa: E501
        'time_created',  # noqa: E501
        'updated',  # noqa: E501
        'self_link',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, name, play_url, pin, topic, author, num_questions, difficulty, time_limit, leaderboard, *args, **kwargs):  # noqa: E501
        """Quiz - a model defined in OpenAPI

        Args:
            name (str, none_type): the display name of this quiz
            play_url (str): URL for playing this quiz
            pin (str): pin code for playing this quiz
            topic (str): the topic of this quiz
            author (str): the id of the quizmaster of this quiz
            num_questions (str): number of questions included in this quiz
            difficulty (float): integer level of difficulty (1-10)
            time_limit (float): number of seconds to respond to each question in this quiz
            leaderboard (QuizLeaderboard):

        Keyword Args:
            questions ([QuizQuestions]): array of question/answer objects included in this quiz. defaults to []  # noqa: E501
            sync (bool): is this quiz synchronous (false == asynchronous). defaults to True  # noqa: E501
            active (bool): is this quiz currently being played?. defaults to False  # noqa: E501
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): unique, system-assigned identifier. [optional]  # noqa: E501
            image_url (str): string containing URL of an image to display for this quiz. [optional]  # noqa: E501
            time_created (datetime): system-assigned creation timestamp. [optional]  # noqa: E501
            updated (datetime): system-assigned update timestamp. [optional]  # noqa: E501
            self_link (str): full URI of the resource. [optional]  # noqa: E501
        """

        questions = kwargs.get('questions', [])
        sync = kwargs.get('sync', True)
        active = kwargs.get('active', False)
        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.name = name
        self.play_url = play_url
        self.pin = pin
        self.topic = topic
        self.author = author
        self.num_questions = num_questions
        self.questions = questions
        self.difficulty = difficulty
        self.time_limit = time_limit
        self.leaderboard = leaderboard
        self.sync = sync
        self.active = active
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, name, play_url, pin, topic, author, num_questions, difficulty, time_limit, leaderboard, *args, **kwargs):  # noqa: E501
        """Quiz - a model defined in OpenAPI

        Args:
            name (str, none_type): the display name of this quiz
            play_url (str): URL for playing this quiz
            pin (str): pin code for playing this quiz
            topic (str): the topic of this quiz
            author (str): the id of the quizmaster of this quiz
            num_questions (str): number of questions included in this quiz
            difficulty (float): integer level of difficulty (1-10)
            time_limit (float): number of seconds to respond to each question in this quiz
            leaderboard (QuizLeaderboard):

        Keyword Args:
            questions ([QuizQuestions]): array of question/answer objects included in this quiz. defaults to []  # noqa: E501
            sync (bool): is this quiz synchronous (false == asynchronous). defaults to True  # noqa: E501
            active (bool): is this quiz currently being played?. defaults to False  # noqa: E501
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): unique, system-assigned identifier. [optional]  # noqa: E501
            image_url (str): string containing URL of an image to display for this quiz. [optional]  # noqa: E501
            time_created (datetime): system-assigned creation timestamp. [optional]  # noqa: E501
            updated (datetime): system-assigned update timestamp. [optional]  # noqa: E501
            self_link (str): full URI of the resource. [optional]  # noqa: E501
        """

        questions = kwargs.get('questions', [])
        sync = kwargs.get('sync', True)
        active = kwargs.get('active', False)
        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.name = name
        self.play_url = play_url
        self.pin = pin
        self.topic = topic
        self.author = author
        self.num_questions = num_questions
        self.questions = questions
        self.difficulty = difficulty
        self.time_limit = time_limit
        self.leaderboard = leaderboard
        self.sync = sync
        self.active = active
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
