// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWY14Mna0pyz15Jcv2jLSq5eVxc2XCHfU',
    appId: '1:338739261213:web:49d62e4552ffaabcbe7bf4',
    messagingSenderId: '338739261213',
    projectId: 'quizrd-prod-382117',
    authDomain: 'quizrd-prod-382117.firebaseapp.com',
    storageBucket: 'quizrd-prod-382117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0nL0No9hEF6pzkXxanGnrxpuFo4uVS4',
    appId: '1:338739261213:android:15cae3ef0f2e55a0be7bf4',
    messagingSenderId: '338739261213',
    projectId: 'quizrd-prod-382117',
    storageBucket: 'quizrd-prod-382117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGB9uaGkJMnMLcRPISIWjibwfMV8xT-kk',
    appId: '1:338739261213:ios:cfab9adc7d4a1563be7bf4',
    messagingSenderId: '338739261213',
    projectId: 'quizrd-prod-382117',
    storageBucket: 'quizrd-prod-382117.appspot.com',
    iosClientId:
        '338739261213-m0c1d09hd977fsqg57vc08d5gpf3oni0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizrd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGB9uaGkJMnMLcRPISIWjibwfMV8xT-kk',
    appId: '1:338739261213:ios:8bb9c6349a0308a3be7bf4',
    messagingSenderId: '338739261213',
    projectId: 'quizrd-prod-382117',
    storageBucket: 'quizrd-prod-382117.appspot.com',
    iosClientId:
        '338739261213-d219mc16cpru3o5qdql8bi6bu0rvnpcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizrd.RunnerTests',
  );
}
