"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-09-01
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.donation import Donation


class TestDonation(unittest.TestCase):
    """Donation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDonation(self):
        """Test Donation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Donation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
