"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-09-01
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.generator import Generator


class TestGenerator(unittest.TestCase):
    """Generator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenerator(self):
        """Test Generator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Generator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
