"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-09-01
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.host import Host


class TestHost(unittest.TestCase):
    """Host unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHost(self):
        """Test Host"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Host()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
