# coding: utf-8

"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-09-01
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.host import Host
from openapi_client import configuration


class TestHost(unittest.TestCase):
    """Host unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
