[tool.poetry]
name = "quizgen"
version = "0.1.0"
description = ""
authors = ["marcacohen <marcacohen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.240"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
