// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHfiNfMhwn7Sny_dlIm8aBkcviX-WlVg',
    appId: '1:780573810218:web:faaa1bb967007e5f2ced53',
    messagingSenderId: '780573810218',
    projectId: 'quizaic',
    authDomain: 'quizaic.firebaseapp.com',
    storageBucket: 'quizaic.appspot.com',
    measurementId: 'G-83X2YBX244',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYErBw1Qi843--baGPFQnmu-4BS7le5aM',
    appId: '1:780573810218:android:6da8796b61f288102ced53',
    messagingSenderId: '780573810218',
    projectId: 'quizaic',
    storageBucket: 'quizaic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo3XFdhtimie_T5ykrXk4RVpOxjXbw5G4',
    appId: '1:780573810218:ios:5c683c1a925d19512ced53',
    messagingSenderId: '780573810218',
    projectId: 'quizaic',
    storageBucket: 'quizaic.appspot.com',
    iosClientId: '780573810218-cs7097lpnvp8ntgp1gr6rl86f2ep61et.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizaic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo3XFdhtimie_T5ykrXk4RVpOxjXbw5G4',
    appId: '1:780573810218:ios:2ff57fbbdd09ff8b2ced53',
    messagingSenderId: '780573810218',
    projectId: 'quizaic',
    storageBucket: 'quizaic.appspot.com',
    iosClientId: '780573810218-rq1ojidaf6o93nhcs58nfbhiolhpkraj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizaic.RunnerTests',
  );
}
