openapi: 3.0.0

info:
  title: Emblem API
  description: REST API for any Emblem server
  version: '2021-09-01'

servers:
- url: https://example.com
  description: Development server

paths:
  /admins:
    get:
      summary: Returns a list of admins
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A JSON array of admins
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Admin'
        '403':
          description: Forbidden
        '404':
          description: not found. The path must have a typo
        default:
          description: Unexpected error

    post:
      summary: Create a new admin
      security:
        - bearerAuth: []
      requestBody:
        description: JSON representation of a single admin
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Admin'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
        '403':
          description: Forbidden
        '404':
          description: admin must have been misspelled in path

  /admins/{id}:
    get:
      summary: returns a single admin
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Admin Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JSON representation of an admin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
        '403':
          description: Forbidden
        '404':
          description: not found
        default:
          description: Unexpected error

    patch:
      summary: updates a single admin
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Admin Id
          required: true
          schema:
            type: string
      requestBody:
        description: JSON representation of a single admin
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Admin'
      responses:
        '201':
          description: JSON representation of an admin 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

    delete:
      summary: deletes a single admin
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Admin Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

  /quizzes:
    get:
      summary: Returns a list of quizzes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A JSON array of quizzes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
        '403':
          description: Forbidden
        '404':
          description: not found. The path must have a typo
        default:
          description: Unexpected error

    post:
      summary: Create a new quiz
      security:
        - bearerAuth: []
      requestBody:
        description: JSON representation of a single quiz
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '403':
          description: Forbidden
        '404':
          description: quizzes must have been misspelled in path

  /quizzes/{id}:
    get:
      summary: returns a single quiz
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Quiz Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JSON representation of a quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '403':
          description: Forbidden
        '404':
          description: not found
        default:
          description: Unexpected error

    patch:
      summary: updates a single quiz
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Quiz Id
          required: true
          schema:
            type: string
      requestBody:
        description: JSON representation of a single quiz
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '201':
          description: JSON representation of a quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

    delete:
      summary: deletes a single quiz
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Quiz Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

  /results:
    get:
      summary: Returns a list of results
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A JSON array of results 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Results'
        '403':
          description: Forbidden
        '404':
          description: not found. The path must have a typo
        default:
          description: Unexpected error

    post:
      summary: Create a new results object (i.e. register a player)
      security:
        - bearerAuth: []
      requestBody:
        description: JSON representation of a (most likely empty) results object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Results'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        '403':
          description: Forbidden
        '404':
          description: results must have been misspelled in path

  /results/{id}:
    get:
      summary: returns a single results object
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Results Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JSON representation of a results object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        '403':
          description: Forbidden
        '404':
          description: not found
        default:
          description: Unexpected error

    patch:
      summary: updates a single results object
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Results Id
          required: true
          schema:
            type: string
      requestBody:
        description: JSON representation of a single results object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Results'
      responses:
        '201':
          description: JSON representation of a results object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

    delete:
      summary: deletes a single results object
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Results Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

  /generators:
    get:
      summary: Returns a list of generators
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A JSON array of generators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Generator'
        '403':
          description: Forbidden
        '404':
          description: not found. The path must have a typo
        default:
          description: Unexpected error

    post:
      summary: Create a new generator
      security:
        - bearerAuth: []
      requestBody:
        description: JSON representation of a single generator
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Generator'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generator'
        '403':
          description: Forbidden
        '404':
          description: generator must have been misspelled in path

  /generators/{id}:
    get:
      summary: returns a single generator
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Generator Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JSON representation of an generator
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generator'
        '403':
          description: Forbidden
        '404':
          description: not found
        default:
          description: Unexpected error

    patch:
      summary: updates a single generator
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Generator Id
          required: true
          schema:
            type: string
      requestBody:
        description: JSON representation of a single generator
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Generator'
      responses:
        '201':
          description: JSON representation of an generator 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generator'
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

    delete:
      summary: deletes a single generator
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Generator Id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
        '403':
          description: Forbidden
        '404':
          description: not found
        '409':
          description: Conflict. If-Match header provided does not match current contents
        default:
          description: Unexpected error

components:
  schemas:
    Admin:
      required:
      - name
      - email
      properties:
        id:
          type: string
          readOnly: true
          description: unique, system-assigned identifier
        name:
          type: string
          description: the display name of this admin
        email:
          type: string
          description: the email address of this admin
        timeCreated:
          type: string
          format: date-time
          readOnly: true
          description: system-assigned creation timestamp
        updated:
          type: string
          format: date-time
          readOnly: true
          description: system-assigned update timestamp
        selfLink:
          type: string
          format: uri
          readOnly: true
          description: full URI of the resource

    Quiz:
      required:
      - name
      properties:
        curQuestion:
          type: integer
          nullable: true
          description: current question number for active quiz or -1 for inactive 
          default: -1
        id:
          type: string
          readOnly: true
          description: unique, system-assigned identifier
        pin:
          type: string
          nullable: true
          description: pin code for playing this quiz
        playUrl:
          type: string
          nullable: true
          description: URL for playing this quiz
        name:
          type: string
          description: the display name of this quiz
        description:
          type: string
          description: a short description of the quiz
        generator:
          type: string 
          description: quiz generator type
        topicFormat:
          type: string 
          description: topic input ("freeform" or "multiple-choice")
        answerFormat:
          type: string 
          description: response input ("freeform" or "multiple-choice")
        topic:
          type: string
          nullable: true
          description: the topic of this quiz
        imageUrl:
          type: string
          description: string containing URL of an image to display for this quiz
          nullable: true
          default: ""
        numQuestions:
          type: string
          description: number of questions included in this quiz
          default: "10"
        numAnswers:
          type: string
          description: number of answers for each question in this quiz (1 == free form)
          default: "4"
        timeLimit:
          type: string
          description: number of seconds to respond to each question in this quiz (3-300)
          default: "30"
        difficulty:
          type: string 
          description: integer level of difficulty (1-5)
          default: "3"
        temperature:
          type: string 
          description: generator temperature (0-1.0)
          default: ".5"
        sync:
          type: boolean
          description: is this quiz synchronous (false == asynchronous)
          nullable: true
          default: true
        anon:
          type: boolean
          description: whether players may be anonymous
          nullable: true
          default: true
        randomQ:
          type: boolean
          description: whether to present questions in random order
          nullable: true
          default: true
        randomA:
          type: boolean
          description: whether to present answers in random order
          nullable: true
          default: true
        survey:
          type: boolean
          description: whether this quiz is an info gathering survey
          nullable: true
          default: false
        QandA:
          type: string 
          nullable: true
          description: json string representation of questions, correct answers, and options
        creator:
          type: string
          nullable: true
          description: the identity of the quiz creator
        active:
          type: boolean
          description: is this quiz currently being played?
          nullable: true
          default: false
        runCount:
          type: integer
          description: number of times quiz has been run
          nullable: true
          default: 0
        timeCreated:
          type: string
          format: date-time
          readOnly: true
          description: system-assigned creation timestamp
        updated:
          type: string
          format: date-time
          readOnly: true
          description: system-assigned update timestamp
        selfLink:
          type: string
          format: uri
          readOnly: true
          description: full URI of the resource

    Results:
      properties:
        id:
          type: string
          readOnly: true
          description: unique, system-assigned identifier
        quiz:
          type: string
          description: id of the quiz associated with these results
        player:
          type: string
          description: id or name of the player associated with these results
        currentQuestion:
          type: integer 
          description: for async mode, number of current question for this player/quiz
        answers:
          type: array
          description: array of responses
          items:
            type: string

    Generator:
      required:
      - name
      properties:
        id:
          type: string
          readOnly: true
          description: unique, system-assigned identifier
        name:
          type: string
          description: the display name of this generator
        freeform:
          type: boolean
          description: whether this generator supports free-form answers
          default: false
        topic_list:
          type: array
          description: array of topics supported by this generator (empty == unlimited)
          items: 
            type: string
        timeCreated:
          type: string
          format: date-time
          readOnly: true
          description: system-assigned creation timestamp
        updated:
          type: string
          format: date-time
          readOnly: true
          description: system-assigned update timestamp
        selfLink:
          type: string
          format: uri
          readOnly: true
          description: full URI of the resource

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
