# coding: utf-8

"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-09-01
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.approvers.get import ApproversGet
from openapi_client.paths.approvers_id.delete import ApproversIdDelete
from openapi_client.paths.approvers_id.get import ApproversIdGet
from openapi_client.paths.approvers_id.patch import ApproversIdPatch
from openapi_client.paths.approvers.post import ApproversPost
from openapi_client.paths.campaigns.get import CampaignsGet
from openapi_client.paths.campaigns_id.delete import CampaignsIdDelete
from openapi_client.paths.campaigns_id_donations.get import CampaignsIdDonationsGet
from openapi_client.paths.campaigns_id.get import CampaignsIdGet
from openapi_client.paths.campaigns_id.patch import CampaignsIdPatch
from openapi_client.paths.campaigns.post import CampaignsPost
from openapi_client.paths.causes.get import CausesGet
from openapi_client.paths.causes_id.delete import CausesIdDelete
from openapi_client.paths.causes_id.get import CausesIdGet
from openapi_client.paths.causes_id.patch import CausesIdPatch
from openapi_client.paths.causes.post import CausesPost
from openapi_client.paths.donations.get import DonationsGet
from openapi_client.paths.donations_id.delete import DonationsIdDelete
from openapi_client.paths.donations_id.get import DonationsIdGet
from openapi_client.paths.donations_id.patch import DonationsIdPatch
from openapi_client.paths.donations.post import DonationsPost
from openapi_client.paths.donors.get import DonorsGet
from openapi_client.paths.donors_id.delete import DonorsIdDelete
from openapi_client.paths.donors_id_donations.get import DonorsIdDonationsGet
from openapi_client.paths.donors_id.get import DonorsIdGet
from openapi_client.paths.donors_id.patch import DonorsIdPatch
from openapi_client.paths.donors.post import DonorsPost
from openapi_client.paths.quizzes.get import QuizzesGet
from openapi_client.paths.quizzes_id.delete import QuizzesIdDelete
from openapi_client.paths.quizzes_id.get import QuizzesIdGet
from openapi_client.paths.quizzes_id.patch import QuizzesIdPatch
from openapi_client.paths.quizzes.post import QuizzesPost


class DefaultApi(
    ApproversGet,
    ApproversIdDelete,
    ApproversIdGet,
    ApproversIdPatch,
    ApproversPost,
    CampaignsGet,
    CampaignsIdDelete,
    CampaignsIdDonationsGet,
    CampaignsIdGet,
    CampaignsIdPatch,
    CampaignsPost,
    CausesGet,
    CausesIdDelete,
    CausesIdGet,
    CausesIdPatch,
    CausesPost,
    DonationsGet,
    DonationsIdDelete,
    DonationsIdGet,
    DonationsIdPatch,
    DonationsPost,
    DonorsGet,
    DonorsIdDelete,
    DonorsIdDonationsGet,
    DonorsIdGet,
    DonorsIdPatch,
    DonorsPost,
    QuizzesGet,
    QuizzesIdDelete,
    QuizzesIdGet,
    QuizzesIdPatch,
    QuizzesPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
